/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PluginsIndexRouteImport } from './routes/plugins/index'
import { Route as PSplatRouteImport } from './routes/p/$'
import { Route as SPluginIdIndexRouteImport } from './routes/s/$pluginId/index'
import { Route as PluginsPluginIdIndexRouteImport } from './routes/plugins/$pluginId/index'
import { Route as SPluginIdFeedRouteImport } from './routes/s/$pluginId/feed'
import { Route as SPluginIdCommunitiesRouteImport } from './routes/s/$pluginId/communities'
import { Route as PluginsPluginIdOptionsRouteImport } from './routes/plugins/$pluginId/options'
import { Route as PluginsPluginIdSplatRouteImport } from './routes/plugins/$pluginId/$'
import { Route as SPluginIdTrendingIndexRouteImport } from './routes/s/$pluginId/trending.index'
import { Route as SPluginIdIIndexRouteImport } from './routes/s/$pluginId/i/index'
import { Route as SPluginIdUserApiIdRouteImport } from './routes/s/$pluginId/user.$apiId'
import { Route as SPluginIdTrendingTopicNameRouteImport } from './routes/s/$pluginId/trending.$topicName'
import { Route as SPluginIdPostApiIdRouteImport } from './routes/s/$pluginId/post.$apiId'
import { Route as SPluginIdCApiIdIndexRouteImport } from './routes/s/$pluginId/c.$apiId.index'
import { Route as SPluginIdIInstanceIdFeedRouteImport } from './routes/s/$pluginId/i/$instanceId/feed'
import { Route as SPluginIdIInstanceIdCommunitiesRouteImport } from './routes/s/$pluginId/i/$instanceId/communities'
import { Route as SPluginIdCCommunityIdPostApiIdRouteImport } from './routes/s/$pluginId/c.$communityId.post.$apiId'
import { Route as SPluginIdIInstanceIdCApiIdIndexRouteImport } from './routes/s/$pluginId/i/$instanceId/c.$apiId.index'
import { Route as SPluginIdIInstanceIdCCommunityIdPostApiIdRouteImport } from './routes/s/$pluginId/i/$instanceId/c.$communityId.post.$apiId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSplatRoute = PSplatRouteImport.update({
  id: '/p/$',
  path: '/p/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SPluginIdIndexRoute = SPluginIdIndexRouteImport.update({
  id: '/s/$pluginId/',
  path: '/s/$pluginId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsPluginIdIndexRoute = PluginsPluginIdIndexRouteImport.update({
  id: '/plugins/$pluginId/',
  path: '/plugins/$pluginId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SPluginIdFeedRoute = SPluginIdFeedRouteImport.update({
  id: '/s/$pluginId/feed',
  path: '/s/$pluginId/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const SPluginIdCommunitiesRoute = SPluginIdCommunitiesRouteImport.update({
  id: '/s/$pluginId/communities',
  path: '/s/$pluginId/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsPluginIdOptionsRoute = PluginsPluginIdOptionsRouteImport.update({
  id: '/plugins/$pluginId/options',
  path: '/plugins/$pluginId/options',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsPluginIdSplatRoute = PluginsPluginIdSplatRouteImport.update({
  id: '/plugins/$pluginId/$',
  path: '/plugins/$pluginId/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SPluginIdTrendingIndexRoute = SPluginIdTrendingIndexRouteImport.update({
  id: '/s/$pluginId/trending/',
  path: '/s/$pluginId/trending/',
  getParentRoute: () => rootRouteImport,
} as any)
const SPluginIdIIndexRoute = SPluginIdIIndexRouteImport.update({
  id: '/s/$pluginId/i/',
  path: '/s/$pluginId/i/',
  getParentRoute: () => rootRouteImport,
} as any)
const SPluginIdUserApiIdRoute = SPluginIdUserApiIdRouteImport.update({
  id: '/s/$pluginId/user/$apiId',
  path: '/s/$pluginId/user/$apiId',
  getParentRoute: () => rootRouteImport,
} as any)
const SPluginIdTrendingTopicNameRoute =
  SPluginIdTrendingTopicNameRouteImport.update({
    id: '/s/$pluginId/trending/$topicName',
    path: '/s/$pluginId/trending/$topicName',
    getParentRoute: () => rootRouteImport,
  } as any)
const SPluginIdPostApiIdRoute = SPluginIdPostApiIdRouteImport.update({
  id: '/s/$pluginId/post/$apiId',
  path: '/s/$pluginId/post/$apiId',
  getParentRoute: () => rootRouteImport,
} as any)
const SPluginIdCApiIdIndexRoute = SPluginIdCApiIdIndexRouteImport.update({
  id: '/s/$pluginId/c/$apiId/',
  path: '/s/$pluginId/c/$apiId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SPluginIdIInstanceIdFeedRoute =
  SPluginIdIInstanceIdFeedRouteImport.update({
    id: '/s/$pluginId/i/$instanceId/feed',
    path: '/s/$pluginId/i/$instanceId/feed',
    getParentRoute: () => rootRouteImport,
  } as any)
const SPluginIdIInstanceIdCommunitiesRoute =
  SPluginIdIInstanceIdCommunitiesRouteImport.update({
    id: '/s/$pluginId/i/$instanceId/communities',
    path: '/s/$pluginId/i/$instanceId/communities',
    getParentRoute: () => rootRouteImport,
  } as any)
const SPluginIdCCommunityIdPostApiIdRoute =
  SPluginIdCCommunityIdPostApiIdRouteImport.update({
    id: '/s/$pluginId/c/$communityId/post/$apiId',
    path: '/s/$pluginId/c/$communityId/post/$apiId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SPluginIdIInstanceIdCApiIdIndexRoute =
  SPluginIdIInstanceIdCApiIdIndexRouteImport.update({
    id: '/s/$pluginId/i/$instanceId/c/$apiId/',
    path: '/s/$pluginId/i/$instanceId/c/$apiId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SPluginIdIInstanceIdCCommunityIdPostApiIdRoute =
  SPluginIdIInstanceIdCCommunityIdPostApiIdRouteImport.update({
    id: '/s/$pluginId/i/$instanceId/c/$communityId/post/$apiId',
    path: '/s/$pluginId/i/$instanceId/c/$communityId/post/$apiId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/favorites': typeof FavoritesRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/p/$': typeof PSplatRoute
  '/plugins/': typeof PluginsIndexRoute
  '/plugins/$pluginId/$': typeof PluginsPluginIdSplatRoute
  '/plugins/$pluginId/options': typeof PluginsPluginIdOptionsRoute
  '/s/$pluginId/communities': typeof SPluginIdCommunitiesRoute
  '/s/$pluginId/feed': typeof SPluginIdFeedRoute
  '/plugins/$pluginId/': typeof PluginsPluginIdIndexRoute
  '/s/$pluginId/': typeof SPluginIdIndexRoute
  '/s/$pluginId/post/$apiId': typeof SPluginIdPostApiIdRoute
  '/s/$pluginId/trending/$topicName': typeof SPluginIdTrendingTopicNameRoute
  '/s/$pluginId/user/$apiId': typeof SPluginIdUserApiIdRoute
  '/s/$pluginId/i/': typeof SPluginIdIIndexRoute
  '/s/$pluginId/trending/': typeof SPluginIdTrendingIndexRoute
  '/s/$pluginId/i/$instanceId/communities': typeof SPluginIdIInstanceIdCommunitiesRoute
  '/s/$pluginId/i/$instanceId/feed': typeof SPluginIdIInstanceIdFeedRoute
  '/s/$pluginId/c/$apiId/': typeof SPluginIdCApiIdIndexRoute
  '/s/$pluginId/c/$communityId/post/$apiId': typeof SPluginIdCCommunityIdPostApiIdRoute
  '/s/$pluginId/i/$instanceId/c/$apiId/': typeof SPluginIdIInstanceIdCApiIdIndexRoute
  '/s/$pluginId/i/$instanceId/c/$communityId/post/$apiId': typeof SPluginIdIInstanceIdCCommunityIdPostApiIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/favorites': typeof FavoritesRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/p/$': typeof PSplatRoute
  '/plugins': typeof PluginsIndexRoute
  '/plugins/$pluginId/$': typeof PluginsPluginIdSplatRoute
  '/plugins/$pluginId/options': typeof PluginsPluginIdOptionsRoute
  '/s/$pluginId/communities': typeof SPluginIdCommunitiesRoute
  '/s/$pluginId/feed': typeof SPluginIdFeedRoute
  '/plugins/$pluginId': typeof PluginsPluginIdIndexRoute
  '/s/$pluginId': typeof SPluginIdIndexRoute
  '/s/$pluginId/post/$apiId': typeof SPluginIdPostApiIdRoute
  '/s/$pluginId/trending/$topicName': typeof SPluginIdTrendingTopicNameRoute
  '/s/$pluginId/user/$apiId': typeof SPluginIdUserApiIdRoute
  '/s/$pluginId/i': typeof SPluginIdIIndexRoute
  '/s/$pluginId/trending': typeof SPluginIdTrendingIndexRoute
  '/s/$pluginId/i/$instanceId/communities': typeof SPluginIdIInstanceIdCommunitiesRoute
  '/s/$pluginId/i/$instanceId/feed': typeof SPluginIdIInstanceIdFeedRoute
  '/s/$pluginId/c/$apiId': typeof SPluginIdCApiIdIndexRoute
  '/s/$pluginId/c/$communityId/post/$apiId': typeof SPluginIdCCommunityIdPostApiIdRoute
  '/s/$pluginId/i/$instanceId/c/$apiId': typeof SPluginIdIInstanceIdCApiIdIndexRoute
  '/s/$pluginId/i/$instanceId/c/$communityId/post/$apiId': typeof SPluginIdIInstanceIdCCommunityIdPostApiIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/favorites': typeof FavoritesRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/p/$': typeof PSplatRoute
  '/plugins/': typeof PluginsIndexRoute
  '/plugins/$pluginId/$': typeof PluginsPluginIdSplatRoute
  '/plugins/$pluginId/options': typeof PluginsPluginIdOptionsRoute
  '/s/$pluginId/communities': typeof SPluginIdCommunitiesRoute
  '/s/$pluginId/feed': typeof SPluginIdFeedRoute
  '/plugins/$pluginId/': typeof PluginsPluginIdIndexRoute
  '/s/$pluginId/': typeof SPluginIdIndexRoute
  '/s/$pluginId/post/$apiId': typeof SPluginIdPostApiIdRoute
  '/s/$pluginId/trending/$topicName': typeof SPluginIdTrendingTopicNameRoute
  '/s/$pluginId/user/$apiId': typeof SPluginIdUserApiIdRoute
  '/s/$pluginId/i/': typeof SPluginIdIIndexRoute
  '/s/$pluginId/trending/': typeof SPluginIdTrendingIndexRoute
  '/s/$pluginId/i/$instanceId/communities': typeof SPluginIdIInstanceIdCommunitiesRoute
  '/s/$pluginId/i/$instanceId/feed': typeof SPluginIdIInstanceIdFeedRoute
  '/s/$pluginId/c/$apiId/': typeof SPluginIdCApiIdIndexRoute
  '/s/$pluginId/c/$communityId/post/$apiId': typeof SPluginIdCCommunityIdPostApiIdRoute
  '/s/$pluginId/i/$instanceId/c/$apiId/': typeof SPluginIdIInstanceIdCApiIdIndexRoute
  '/s/$pluginId/i/$instanceId/c/$communityId/post/$apiId': typeof SPluginIdIInstanceIdCCommunityIdPostApiIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/donate'
    | '/favorites'
    | '/privacy'
    | '/settings'
    | '/p/$'
    | '/plugins/'
    | '/plugins/$pluginId/$'
    | '/plugins/$pluginId/options'
    | '/s/$pluginId/communities'
    | '/s/$pluginId/feed'
    | '/plugins/$pluginId/'
    | '/s/$pluginId/'
    | '/s/$pluginId/post/$apiId'
    | '/s/$pluginId/trending/$topicName'
    | '/s/$pluginId/user/$apiId'
    | '/s/$pluginId/i/'
    | '/s/$pluginId/trending/'
    | '/s/$pluginId/i/$instanceId/communities'
    | '/s/$pluginId/i/$instanceId/feed'
    | '/s/$pluginId/c/$apiId/'
    | '/s/$pluginId/c/$communityId/post/$apiId'
    | '/s/$pluginId/i/$instanceId/c/$apiId/'
    | '/s/$pluginId/i/$instanceId/c/$communityId/post/$apiId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/donate'
    | '/favorites'
    | '/privacy'
    | '/settings'
    | '/p/$'
    | '/plugins'
    | '/plugins/$pluginId/$'
    | '/plugins/$pluginId/options'
    | '/s/$pluginId/communities'
    | '/s/$pluginId/feed'
    | '/plugins/$pluginId'
    | '/s/$pluginId'
    | '/s/$pluginId/post/$apiId'
    | '/s/$pluginId/trending/$topicName'
    | '/s/$pluginId/user/$apiId'
    | '/s/$pluginId/i'
    | '/s/$pluginId/trending'
    | '/s/$pluginId/i/$instanceId/communities'
    | '/s/$pluginId/i/$instanceId/feed'
    | '/s/$pluginId/c/$apiId'
    | '/s/$pluginId/c/$communityId/post/$apiId'
    | '/s/$pluginId/i/$instanceId/c/$apiId'
    | '/s/$pluginId/i/$instanceId/c/$communityId/post/$apiId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/donate'
    | '/favorites'
    | '/privacy'
    | '/settings'
    | '/p/$'
    | '/plugins/'
    | '/plugins/$pluginId/$'
    | '/plugins/$pluginId/options'
    | '/s/$pluginId/communities'
    | '/s/$pluginId/feed'
    | '/plugins/$pluginId/'
    | '/s/$pluginId/'
    | '/s/$pluginId/post/$apiId'
    | '/s/$pluginId/trending/$topicName'
    | '/s/$pluginId/user/$apiId'
    | '/s/$pluginId/i/'
    | '/s/$pluginId/trending/'
    | '/s/$pluginId/i/$instanceId/communities'
    | '/s/$pluginId/i/$instanceId/feed'
    | '/s/$pluginId/c/$apiId/'
    | '/s/$pluginId/c/$communityId/post/$apiId'
    | '/s/$pluginId/i/$instanceId/c/$apiId/'
    | '/s/$pluginId/i/$instanceId/c/$communityId/post/$apiId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DonateRoute: typeof DonateRoute
  FavoritesRoute: typeof FavoritesRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  PSplatRoute: typeof PSplatRoute
  PluginsIndexRoute: typeof PluginsIndexRoute
  PluginsPluginIdSplatRoute: typeof PluginsPluginIdSplatRoute
  PluginsPluginIdOptionsRoute: typeof PluginsPluginIdOptionsRoute
  SPluginIdCommunitiesRoute: typeof SPluginIdCommunitiesRoute
  SPluginIdFeedRoute: typeof SPluginIdFeedRoute
  PluginsPluginIdIndexRoute: typeof PluginsPluginIdIndexRoute
  SPluginIdIndexRoute: typeof SPluginIdIndexRoute
  SPluginIdPostApiIdRoute: typeof SPluginIdPostApiIdRoute
  SPluginIdTrendingTopicNameRoute: typeof SPluginIdTrendingTopicNameRoute
  SPluginIdUserApiIdRoute: typeof SPluginIdUserApiIdRoute
  SPluginIdIIndexRoute: typeof SPluginIdIIndexRoute
  SPluginIdTrendingIndexRoute: typeof SPluginIdTrendingIndexRoute
  SPluginIdIInstanceIdCommunitiesRoute: typeof SPluginIdIInstanceIdCommunitiesRoute
  SPluginIdIInstanceIdFeedRoute: typeof SPluginIdIInstanceIdFeedRoute
  SPluginIdCApiIdIndexRoute: typeof SPluginIdCApiIdIndexRoute
  SPluginIdCCommunityIdPostApiIdRoute: typeof SPluginIdCCommunityIdPostApiIdRoute
  SPluginIdIInstanceIdCApiIdIndexRoute: typeof SPluginIdIInstanceIdCApiIdIndexRoute
  SPluginIdIInstanceIdCCommunityIdPostApiIdRoute: typeof SPluginIdIInstanceIdCCommunityIdPostApiIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof PluginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$': {
      id: '/p/$'
      path: '/p/$'
      fullPath: '/p/$'
      preLoaderRoute: typeof PSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$pluginId/': {
      id: '/s/$pluginId/'
      path: '/s/$pluginId'
      fullPath: '/s/$pluginId/'
      preLoaderRoute: typeof SPluginIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/': {
      id: '/plugins/$pluginId/'
      path: '/plugins/$pluginId'
      fullPath: '/plugins/$pluginId/'
      preLoaderRoute: typeof PluginsPluginIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$pluginId/feed': {
      id: '/s/$pluginId/feed'
      path: '/s/$pluginId/feed'
      fullPath: '/s/$pluginId/feed'
      preLoaderRoute: typeof SPluginIdFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$pluginId/communities': {
      id: '/s/$pluginId/communities'
      path: '/s/$pluginId/communities'
      fullPath: '/s/$pluginId/communities'
      preLoaderRoute: typeof SPluginIdCommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/options': {
      id: '/plugins/$pluginId/options'
      path: '/plugins/$pluginId/options'
      fullPath: '/plugins/$pluginId/options'
      preLoaderRoute: typeof PluginsPluginIdOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/$': {
      id: '/plugins/$pluginId/$'
      path: '/plugins/$pluginId/$'
      fullPath: '/plugins/$pluginId/$'
      preLoaderRoute: typeof PluginsPluginIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$pluginId/trending/': {
      id: '/s/$pluginId/trending/'
      path: '/s/$pluginId/trending'
      fullPath: '/s/$pluginId/trending/'
      preLoaderRoute: typeof SPluginIdTrendingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$pluginId/i/': {
      id: '/s/$pluginId/i/'
      path: '/s/$pluginId/i'
      fullPath: '/s/$pluginId/i/'
      preLoaderRoute: typeof SPluginIdIIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$pluginId/user/$apiId': {
      id: '/s/$pluginId/user/$apiId'
      path: '/s/$pluginId/user/$apiId'
      fullPath: '/s/$pluginId/user/$apiId'
      preLoaderRoute: typeof SPluginIdUserApiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$pluginId/trending/$topicName': {
      id: '/s/$pluginId/trending/$topicName'
      path: '/s/$pluginId/trending/$topicName'
      fullPath: '/s/$pluginId/trending/$topicName'
      preLoaderRoute: typeof SPluginIdTrendingTopicNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$pluginId/post/$apiId': {
      id: '/s/$pluginId/post/$apiId'
      path: '/s/$pluginId/post/$apiId'
      fullPath: '/s/$pluginId/post/$apiId'
      preLoaderRoute: typeof SPluginIdPostApiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$pluginId/c/$apiId/': {
      id: '/s/$pluginId/c/$apiId/'
      path: '/s/$pluginId/c/$apiId'
      fullPath: '/s/$pluginId/c/$apiId/'
      preLoaderRoute: typeof SPluginIdCApiIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$pluginId/i/$instanceId/feed': {
      id: '/s/$pluginId/i/$instanceId/feed'
      path: '/s/$pluginId/i/$instanceId/feed'
      fullPath: '/s/$pluginId/i/$instanceId/feed'
      preLoaderRoute: typeof SPluginIdIInstanceIdFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$pluginId/i/$instanceId/communities': {
      id: '/s/$pluginId/i/$instanceId/communities'
      path: '/s/$pluginId/i/$instanceId/communities'
      fullPath: '/s/$pluginId/i/$instanceId/communities'
      preLoaderRoute: typeof SPluginIdIInstanceIdCommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$pluginId/c/$communityId/post/$apiId': {
      id: '/s/$pluginId/c/$communityId/post/$apiId'
      path: '/s/$pluginId/c/$communityId/post/$apiId'
      fullPath: '/s/$pluginId/c/$communityId/post/$apiId'
      preLoaderRoute: typeof SPluginIdCCommunityIdPostApiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$pluginId/i/$instanceId/c/$apiId/': {
      id: '/s/$pluginId/i/$instanceId/c/$apiId/'
      path: '/s/$pluginId/i/$instanceId/c/$apiId'
      fullPath: '/s/$pluginId/i/$instanceId/c/$apiId/'
      preLoaderRoute: typeof SPluginIdIInstanceIdCApiIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$pluginId/i/$instanceId/c/$communityId/post/$apiId': {
      id: '/s/$pluginId/i/$instanceId/c/$communityId/post/$apiId'
      path: '/s/$pluginId/i/$instanceId/c/$communityId/post/$apiId'
      fullPath: '/s/$pluginId/i/$instanceId/c/$communityId/post/$apiId'
      preLoaderRoute: typeof SPluginIdIInstanceIdCCommunityIdPostApiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DonateRoute: DonateRoute,
  FavoritesRoute: FavoritesRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  PSplatRoute: PSplatRoute,
  PluginsIndexRoute: PluginsIndexRoute,
  PluginsPluginIdSplatRoute: PluginsPluginIdSplatRoute,
  PluginsPluginIdOptionsRoute: PluginsPluginIdOptionsRoute,
  SPluginIdCommunitiesRoute: SPluginIdCommunitiesRoute,
  SPluginIdFeedRoute: SPluginIdFeedRoute,
  PluginsPluginIdIndexRoute: PluginsPluginIdIndexRoute,
  SPluginIdIndexRoute: SPluginIdIndexRoute,
  SPluginIdPostApiIdRoute: SPluginIdPostApiIdRoute,
  SPluginIdTrendingTopicNameRoute: SPluginIdTrendingTopicNameRoute,
  SPluginIdUserApiIdRoute: SPluginIdUserApiIdRoute,
  SPluginIdIIndexRoute: SPluginIdIIndexRoute,
  SPluginIdTrendingIndexRoute: SPluginIdTrendingIndexRoute,
  SPluginIdIInstanceIdCommunitiesRoute: SPluginIdIInstanceIdCommunitiesRoute,
  SPluginIdIInstanceIdFeedRoute: SPluginIdIInstanceIdFeedRoute,
  SPluginIdCApiIdIndexRoute: SPluginIdCApiIdIndexRoute,
  SPluginIdCCommunityIdPostApiIdRoute: SPluginIdCCommunityIdPostApiIdRoute,
  SPluginIdIInstanceIdCApiIdIndexRoute: SPluginIdIInstanceIdCApiIdIndexRoute,
  SPluginIdIInstanceIdCCommunityIdPostApiIdRoute:
    SPluginIdIInstanceIdCCommunityIdPostApiIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
