/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PluginsIndexRouteImport } from './routes/plugins/index'
import { Route as PluginsPluginIdIndexRouteImport } from './routes/plugins/$pluginId/index'
import { Route as PluginsPluginIdOptionsRouteImport } from './routes/plugins/$pluginId/options'
import { Route as PluginsPluginIdFeedRouteImport } from './routes/plugins/$pluginId/feed'
import { Route as PluginsPluginIdTrendingIndexRouteImport } from './routes/plugins/$pluginId/trending.index'
import { Route as PluginsPluginIdInstancesIndexRouteImport } from './routes/plugins/$pluginId/instances/index'
import { Route as PluginsPluginIdUserApiIdRouteImport } from './routes/plugins/$pluginId/user.$apiId'
import { Route as PluginsPluginIdTrendingTopicNameRouteImport } from './routes/plugins/$pluginId/trending.$topicName'
import { Route as PluginsPluginIdPostApiIdRouteImport } from './routes/plugins/$pluginId/post.$apiId'
import { Route as PluginsPluginIdCommunityApiIdIndexRouteImport } from './routes/plugins/$pluginId/community.$apiId.index'
import { Route as PluginsPluginIdInstancesInstanceIdFeedRouteImport } from './routes/plugins/$pluginId/instances/$instanceId/feed'
import { Route as PluginsPluginIdInstancesInstanceIdCommunitiesRouteImport } from './routes/plugins/$pluginId/instances/$instanceId/communities'
import { Route as PluginsPluginIdCommunityCommunityIdPostApiIdRouteImport } from './routes/plugins/$pluginId/community.$communityId.post.$apiId'
import { Route as PluginsPluginIdInstancesInstanceIdCommunityApiIdIndexRouteImport } from './routes/plugins/$pluginId/instances/$instanceId/community.$apiId.index'
import { Route as PluginsPluginIdInstancesInstanceIdCommunityCommunityIdPostApiIdRouteImport } from './routes/plugins/$pluginId/instances/$instanceId/community.$communityId.post.$apiId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsPluginIdIndexRoute = PluginsPluginIdIndexRouteImport.update({
  id: '/plugins/$pluginId/',
  path: '/plugins/$pluginId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsPluginIdOptionsRoute = PluginsPluginIdOptionsRouteImport.update({
  id: '/plugins/$pluginId/options',
  path: '/plugins/$pluginId/options',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsPluginIdFeedRoute = PluginsPluginIdFeedRouteImport.update({
  id: '/plugins/$pluginId/feed',
  path: '/plugins/$pluginId/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsPluginIdTrendingIndexRoute =
  PluginsPluginIdTrendingIndexRouteImport.update({
    id: '/plugins/$pluginId/trending/',
    path: '/plugins/$pluginId/trending/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PluginsPluginIdInstancesIndexRoute =
  PluginsPluginIdInstancesIndexRouteImport.update({
    id: '/plugins/$pluginId/instances/',
    path: '/plugins/$pluginId/instances/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PluginsPluginIdUserApiIdRoute =
  PluginsPluginIdUserApiIdRouteImport.update({
    id: '/plugins/$pluginId/user/$apiId',
    path: '/plugins/$pluginId/user/$apiId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PluginsPluginIdTrendingTopicNameRoute =
  PluginsPluginIdTrendingTopicNameRouteImport.update({
    id: '/plugins/$pluginId/trending/$topicName',
    path: '/plugins/$pluginId/trending/$topicName',
    getParentRoute: () => rootRouteImport,
  } as any)
const PluginsPluginIdPostApiIdRoute =
  PluginsPluginIdPostApiIdRouteImport.update({
    id: '/plugins/$pluginId/post/$apiId',
    path: '/plugins/$pluginId/post/$apiId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PluginsPluginIdCommunityApiIdIndexRoute =
  PluginsPluginIdCommunityApiIdIndexRouteImport.update({
    id: '/plugins/$pluginId/community/$apiId/',
    path: '/plugins/$pluginId/community/$apiId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PluginsPluginIdInstancesInstanceIdFeedRoute =
  PluginsPluginIdInstancesInstanceIdFeedRouteImport.update({
    id: '/plugins/$pluginId/instances/$instanceId/feed',
    path: '/plugins/$pluginId/instances/$instanceId/feed',
    getParentRoute: () => rootRouteImport,
  } as any)
const PluginsPluginIdInstancesInstanceIdCommunitiesRoute =
  PluginsPluginIdInstancesInstanceIdCommunitiesRouteImport.update({
    id: '/plugins/$pluginId/instances/$instanceId/communities',
    path: '/plugins/$pluginId/instances/$instanceId/communities',
    getParentRoute: () => rootRouteImport,
  } as any)
const PluginsPluginIdCommunityCommunityIdPostApiIdRoute =
  PluginsPluginIdCommunityCommunityIdPostApiIdRouteImport.update({
    id: '/plugins/$pluginId/community/$communityId/post/$apiId',
    path: '/plugins/$pluginId/community/$communityId/post/$apiId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PluginsPluginIdInstancesInstanceIdCommunityApiIdIndexRoute =
  PluginsPluginIdInstancesInstanceIdCommunityApiIdIndexRouteImport.update({
    id: '/plugins/$pluginId/instances/$instanceId/community/$apiId/',
    path: '/plugins/$pluginId/instances/$instanceId/community/$apiId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PluginsPluginIdInstancesInstanceIdCommunityCommunityIdPostApiIdRoute =
  PluginsPluginIdInstancesInstanceIdCommunityCommunityIdPostApiIdRouteImport.update(
    {
      id: '/plugins/$pluginId/instances/$instanceId/community/$communityId/post/$apiId',
      path: '/plugins/$pluginId/instances/$instanceId/community/$communityId/post/$apiId',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/settings': typeof SettingsRoute
  '/plugins/': typeof PluginsIndexRoute
  '/plugins/$pluginId/feed': typeof PluginsPluginIdFeedRoute
  '/plugins/$pluginId/options': typeof PluginsPluginIdOptionsRoute
  '/plugins/$pluginId/': typeof PluginsPluginIdIndexRoute
  '/plugins/$pluginId/post/$apiId': typeof PluginsPluginIdPostApiIdRoute
  '/plugins/$pluginId/trending/$topicName': typeof PluginsPluginIdTrendingTopicNameRoute
  '/plugins/$pluginId/user/$apiId': typeof PluginsPluginIdUserApiIdRoute
  '/plugins/$pluginId/instances/': typeof PluginsPluginIdInstancesIndexRoute
  '/plugins/$pluginId/trending/': typeof PluginsPluginIdTrendingIndexRoute
  '/plugins/$pluginId/instances/$instanceId/communities': typeof PluginsPluginIdInstancesInstanceIdCommunitiesRoute
  '/plugins/$pluginId/instances/$instanceId/feed': typeof PluginsPluginIdInstancesInstanceIdFeedRoute
  '/plugins/$pluginId/community/$apiId/': typeof PluginsPluginIdCommunityApiIdIndexRoute
  '/plugins/$pluginId/community/$communityId/post/$apiId': typeof PluginsPluginIdCommunityCommunityIdPostApiIdRoute
  '/plugins/$pluginId/instances/$instanceId/community/$apiId/': typeof PluginsPluginIdInstancesInstanceIdCommunityApiIdIndexRoute
  '/plugins/$pluginId/instances/$instanceId/community/$communityId/post/$apiId': typeof PluginsPluginIdInstancesInstanceIdCommunityCommunityIdPostApiIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/settings': typeof SettingsRoute
  '/plugins': typeof PluginsIndexRoute
  '/plugins/$pluginId/feed': typeof PluginsPluginIdFeedRoute
  '/plugins/$pluginId/options': typeof PluginsPluginIdOptionsRoute
  '/plugins/$pluginId': typeof PluginsPluginIdIndexRoute
  '/plugins/$pluginId/post/$apiId': typeof PluginsPluginIdPostApiIdRoute
  '/plugins/$pluginId/trending/$topicName': typeof PluginsPluginIdTrendingTopicNameRoute
  '/plugins/$pluginId/user/$apiId': typeof PluginsPluginIdUserApiIdRoute
  '/plugins/$pluginId/instances': typeof PluginsPluginIdInstancesIndexRoute
  '/plugins/$pluginId/trending': typeof PluginsPluginIdTrendingIndexRoute
  '/plugins/$pluginId/instances/$instanceId/communities': typeof PluginsPluginIdInstancesInstanceIdCommunitiesRoute
  '/plugins/$pluginId/instances/$instanceId/feed': typeof PluginsPluginIdInstancesInstanceIdFeedRoute
  '/plugins/$pluginId/community/$apiId': typeof PluginsPluginIdCommunityApiIdIndexRoute
  '/plugins/$pluginId/community/$communityId/post/$apiId': typeof PluginsPluginIdCommunityCommunityIdPostApiIdRoute
  '/plugins/$pluginId/instances/$instanceId/community/$apiId': typeof PluginsPluginIdInstancesInstanceIdCommunityApiIdIndexRoute
  '/plugins/$pluginId/instances/$instanceId/community/$communityId/post/$apiId': typeof PluginsPluginIdInstancesInstanceIdCommunityCommunityIdPostApiIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/settings': typeof SettingsRoute
  '/plugins/': typeof PluginsIndexRoute
  '/plugins/$pluginId/feed': typeof PluginsPluginIdFeedRoute
  '/plugins/$pluginId/options': typeof PluginsPluginIdOptionsRoute
  '/plugins/$pluginId/': typeof PluginsPluginIdIndexRoute
  '/plugins/$pluginId/post/$apiId': typeof PluginsPluginIdPostApiIdRoute
  '/plugins/$pluginId/trending/$topicName': typeof PluginsPluginIdTrendingTopicNameRoute
  '/plugins/$pluginId/user/$apiId': typeof PluginsPluginIdUserApiIdRoute
  '/plugins/$pluginId/instances/': typeof PluginsPluginIdInstancesIndexRoute
  '/plugins/$pluginId/trending/': typeof PluginsPluginIdTrendingIndexRoute
  '/plugins/$pluginId/instances/$instanceId/communities': typeof PluginsPluginIdInstancesInstanceIdCommunitiesRoute
  '/plugins/$pluginId/instances/$instanceId/feed': typeof PluginsPluginIdInstancesInstanceIdFeedRoute
  '/plugins/$pluginId/community/$apiId/': typeof PluginsPluginIdCommunityApiIdIndexRoute
  '/plugins/$pluginId/community/$communityId/post/$apiId': typeof PluginsPluginIdCommunityCommunityIdPostApiIdRoute
  '/plugins/$pluginId/instances/$instanceId/community/$apiId/': typeof PluginsPluginIdInstancesInstanceIdCommunityApiIdIndexRoute
  '/plugins/$pluginId/instances/$instanceId/community/$communityId/post/$apiId': typeof PluginsPluginIdInstancesInstanceIdCommunityCommunityIdPostApiIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/settings'
    | '/plugins/'
    | '/plugins/$pluginId/feed'
    | '/plugins/$pluginId/options'
    | '/plugins/$pluginId/'
    | '/plugins/$pluginId/post/$apiId'
    | '/plugins/$pluginId/trending/$topicName'
    | '/plugins/$pluginId/user/$apiId'
    | '/plugins/$pluginId/instances/'
    | '/plugins/$pluginId/trending/'
    | '/plugins/$pluginId/instances/$instanceId/communities'
    | '/plugins/$pluginId/instances/$instanceId/feed'
    | '/plugins/$pluginId/community/$apiId/'
    | '/plugins/$pluginId/community/$communityId/post/$apiId'
    | '/plugins/$pluginId/instances/$instanceId/community/$apiId/'
    | '/plugins/$pluginId/instances/$instanceId/community/$communityId/post/$apiId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/settings'
    | '/plugins'
    | '/plugins/$pluginId/feed'
    | '/plugins/$pluginId/options'
    | '/plugins/$pluginId'
    | '/plugins/$pluginId/post/$apiId'
    | '/plugins/$pluginId/trending/$topicName'
    | '/plugins/$pluginId/user/$apiId'
    | '/plugins/$pluginId/instances'
    | '/plugins/$pluginId/trending'
    | '/plugins/$pluginId/instances/$instanceId/communities'
    | '/plugins/$pluginId/instances/$instanceId/feed'
    | '/plugins/$pluginId/community/$apiId'
    | '/plugins/$pluginId/community/$communityId/post/$apiId'
    | '/plugins/$pluginId/instances/$instanceId/community/$apiId'
    | '/plugins/$pluginId/instances/$instanceId/community/$communityId/post/$apiId'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/settings'
    | '/plugins/'
    | '/plugins/$pluginId/feed'
    | '/plugins/$pluginId/options'
    | '/plugins/$pluginId/'
    | '/plugins/$pluginId/post/$apiId'
    | '/plugins/$pluginId/trending/$topicName'
    | '/plugins/$pluginId/user/$apiId'
    | '/plugins/$pluginId/instances/'
    | '/plugins/$pluginId/trending/'
    | '/plugins/$pluginId/instances/$instanceId/communities'
    | '/plugins/$pluginId/instances/$instanceId/feed'
    | '/plugins/$pluginId/community/$apiId/'
    | '/plugins/$pluginId/community/$communityId/post/$apiId'
    | '/plugins/$pluginId/instances/$instanceId/community/$apiId/'
    | '/plugins/$pluginId/instances/$instanceId/community/$communityId/post/$apiId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  SettingsRoute: typeof SettingsRoute
  PluginsIndexRoute: typeof PluginsIndexRoute
  PluginsPluginIdFeedRoute: typeof PluginsPluginIdFeedRoute
  PluginsPluginIdOptionsRoute: typeof PluginsPluginIdOptionsRoute
  PluginsPluginIdIndexRoute: typeof PluginsPluginIdIndexRoute
  PluginsPluginIdPostApiIdRoute: typeof PluginsPluginIdPostApiIdRoute
  PluginsPluginIdTrendingTopicNameRoute: typeof PluginsPluginIdTrendingTopicNameRoute
  PluginsPluginIdUserApiIdRoute: typeof PluginsPluginIdUserApiIdRoute
  PluginsPluginIdInstancesIndexRoute: typeof PluginsPluginIdInstancesIndexRoute
  PluginsPluginIdTrendingIndexRoute: typeof PluginsPluginIdTrendingIndexRoute
  PluginsPluginIdInstancesInstanceIdCommunitiesRoute: typeof PluginsPluginIdInstancesInstanceIdCommunitiesRoute
  PluginsPluginIdInstancesInstanceIdFeedRoute: typeof PluginsPluginIdInstancesInstanceIdFeedRoute
  PluginsPluginIdCommunityApiIdIndexRoute: typeof PluginsPluginIdCommunityApiIdIndexRoute
  PluginsPluginIdCommunityCommunityIdPostApiIdRoute: typeof PluginsPluginIdCommunityCommunityIdPostApiIdRoute
  PluginsPluginIdInstancesInstanceIdCommunityApiIdIndexRoute: typeof PluginsPluginIdInstancesInstanceIdCommunityApiIdIndexRoute
  PluginsPluginIdInstancesInstanceIdCommunityCommunityIdPostApiIdRoute: typeof PluginsPluginIdInstancesInstanceIdCommunityCommunityIdPostApiIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof PluginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/': {
      id: '/plugins/$pluginId/'
      path: '/plugins/$pluginId'
      fullPath: '/plugins/$pluginId/'
      preLoaderRoute: typeof PluginsPluginIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/options': {
      id: '/plugins/$pluginId/options'
      path: '/plugins/$pluginId/options'
      fullPath: '/plugins/$pluginId/options'
      preLoaderRoute: typeof PluginsPluginIdOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/feed': {
      id: '/plugins/$pluginId/feed'
      path: '/plugins/$pluginId/feed'
      fullPath: '/plugins/$pluginId/feed'
      preLoaderRoute: typeof PluginsPluginIdFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/trending/': {
      id: '/plugins/$pluginId/trending/'
      path: '/plugins/$pluginId/trending'
      fullPath: '/plugins/$pluginId/trending/'
      preLoaderRoute: typeof PluginsPluginIdTrendingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/instances/': {
      id: '/plugins/$pluginId/instances/'
      path: '/plugins/$pluginId/instances'
      fullPath: '/plugins/$pluginId/instances/'
      preLoaderRoute: typeof PluginsPluginIdInstancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/user/$apiId': {
      id: '/plugins/$pluginId/user/$apiId'
      path: '/plugins/$pluginId/user/$apiId'
      fullPath: '/plugins/$pluginId/user/$apiId'
      preLoaderRoute: typeof PluginsPluginIdUserApiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/trending/$topicName': {
      id: '/plugins/$pluginId/trending/$topicName'
      path: '/plugins/$pluginId/trending/$topicName'
      fullPath: '/plugins/$pluginId/trending/$topicName'
      preLoaderRoute: typeof PluginsPluginIdTrendingTopicNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/post/$apiId': {
      id: '/plugins/$pluginId/post/$apiId'
      path: '/plugins/$pluginId/post/$apiId'
      fullPath: '/plugins/$pluginId/post/$apiId'
      preLoaderRoute: typeof PluginsPluginIdPostApiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/community/$apiId/': {
      id: '/plugins/$pluginId/community/$apiId/'
      path: '/plugins/$pluginId/community/$apiId'
      fullPath: '/plugins/$pluginId/community/$apiId/'
      preLoaderRoute: typeof PluginsPluginIdCommunityApiIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/instances/$instanceId/feed': {
      id: '/plugins/$pluginId/instances/$instanceId/feed'
      path: '/plugins/$pluginId/instances/$instanceId/feed'
      fullPath: '/plugins/$pluginId/instances/$instanceId/feed'
      preLoaderRoute: typeof PluginsPluginIdInstancesInstanceIdFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/instances/$instanceId/communities': {
      id: '/plugins/$pluginId/instances/$instanceId/communities'
      path: '/plugins/$pluginId/instances/$instanceId/communities'
      fullPath: '/plugins/$pluginId/instances/$instanceId/communities'
      preLoaderRoute: typeof PluginsPluginIdInstancesInstanceIdCommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/community/$communityId/post/$apiId': {
      id: '/plugins/$pluginId/community/$communityId/post/$apiId'
      path: '/plugins/$pluginId/community/$communityId/post/$apiId'
      fullPath: '/plugins/$pluginId/community/$communityId/post/$apiId'
      preLoaderRoute: typeof PluginsPluginIdCommunityCommunityIdPostApiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/instances/$instanceId/community/$apiId/': {
      id: '/plugins/$pluginId/instances/$instanceId/community/$apiId/'
      path: '/plugins/$pluginId/instances/$instanceId/community/$apiId'
      fullPath: '/plugins/$pluginId/instances/$instanceId/community/$apiId/'
      preLoaderRoute: typeof PluginsPluginIdInstancesInstanceIdCommunityApiIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$pluginId/instances/$instanceId/community/$communityId/post/$apiId': {
      id: '/plugins/$pluginId/instances/$instanceId/community/$communityId/post/$apiId'
      path: '/plugins/$pluginId/instances/$instanceId/community/$communityId/post/$apiId'
      fullPath: '/plugins/$pluginId/instances/$instanceId/community/$communityId/post/$apiId'
      preLoaderRoute: typeof PluginsPluginIdInstancesInstanceIdCommunityCommunityIdPostApiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  SettingsRoute: SettingsRoute,
  PluginsIndexRoute: PluginsIndexRoute,
  PluginsPluginIdFeedRoute: PluginsPluginIdFeedRoute,
  PluginsPluginIdOptionsRoute: PluginsPluginIdOptionsRoute,
  PluginsPluginIdIndexRoute: PluginsPluginIdIndexRoute,
  PluginsPluginIdPostApiIdRoute: PluginsPluginIdPostApiIdRoute,
  PluginsPluginIdTrendingTopicNameRoute: PluginsPluginIdTrendingTopicNameRoute,
  PluginsPluginIdUserApiIdRoute: PluginsPluginIdUserApiIdRoute,
  PluginsPluginIdInstancesIndexRoute: PluginsPluginIdInstancesIndexRoute,
  PluginsPluginIdTrendingIndexRoute: PluginsPluginIdTrendingIndexRoute,
  PluginsPluginIdInstancesInstanceIdCommunitiesRoute:
    PluginsPluginIdInstancesInstanceIdCommunitiesRoute,
  PluginsPluginIdInstancesInstanceIdFeedRoute:
    PluginsPluginIdInstancesInstanceIdFeedRoute,
  PluginsPluginIdCommunityApiIdIndexRoute:
    PluginsPluginIdCommunityApiIdIndexRoute,
  PluginsPluginIdCommunityCommunityIdPostApiIdRoute:
    PluginsPluginIdCommunityCommunityIdPostApiIdRoute,
  PluginsPluginIdInstancesInstanceIdCommunityApiIdIndexRoute:
    PluginsPluginIdInstancesInstanceIdCommunityApiIdIndexRoute,
  PluginsPluginIdInstancesInstanceIdCommunityCommunityIdPostApiIdRoute:
    PluginsPluginIdInstancesInstanceIdCommunityCommunityIdPostApiIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
